### ISSUE TITLE
Maintenence team.md hyperlink leads to 404 - page not found error

### ISSUE THREAD

**Issue by AGunnarP** [kochas23/Threat-Watch#110]
For more details about each team member's role and responsibilities, please refer to the [Maintenance Team Documentation](https://github.com/kochas23/Threat-Watch/blob/Core/%CE%9Caintenance%20Team.md) and the [Security Team Documentation](https://github.com/kochas23/Threat-Watch/blob/Core/Security%20Team.md).

**Comment by Konstantinos-Chatzistavrou** [comment]
Resolved
