### ISSUE TITLE
Security Team hyperlink leads to a 404 not found error

### ISSUE THREAD

**Issue by AGunnarP** [kochas23/Threat-Watch#111]
For more details about each team member's role and responsibilities, please refer to the [Maintenance Team Documentation](https://github.com/kochas23/Threat-Watch/blob/Core/%CE%9Caintenance%20Team.md) and the [Security Team Documentation](https://github.com/kochas23/Threat-Watch/blob/Core/Security%20Team.md).

**Comment by Konstantinos-Chatzistavrou** [comment]
I am gonna look into it. Thanks for reporting it.

**Comment by Konstantinos-Chatzistavrou** [comment]
Resolved
